{% set version = "2.2.21" %}

package:
  name: udunits2
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-{{ version }}.tar.gz
  sha256: 9b75f5ff0484adddbaf04924e8af3d3c9fb4b31cc5524c3d4b80b4c1307d1a7d

build:
  number: 0
  skip:  True  # [py>35]
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - automake  # [not win]
    - libtool  # [not win]
    - texinfo  # [not win]
    - expat
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - expat
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles
    - conda inspect linkages -p $PREFIX udunits2  # [not win]
    - conda inspect objects -p $PREFIX udunits2  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: UCAR OSI approved
  license_file: COPYRIGHT
  summary: 'The UDUNITS package supports units of physical quantities.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - dkillick
