{% set version = "2.2.25" %}
{% set p = 'm2-' if win else '' %}
{% set n = 'm2w64-' if win else '' %}

package:
  name: udunits2        # [unix]
  name: m2w64-udunits2  # [win]
  version: {{ version }}

source:
  git_url: https://github.com/Unidata/UDUNITS-2
  git_tag: v{{ version }}
  patches:
    - 0001-Win-32-Fix-shared-library-build.patch
    - 0002-Use-the-shared-library-to-locate-the-default-xml.patch

build:
  number: 1
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}    # [unix]
    - {{n}}toolchain         # [win]
    - {{p}}git
    - {{p}}autoconf
    - {{p}}automake          # [unix]
    - {{p}}automake-wrapper  # [win]
    - {{p}}texinfo
    - {{p}}libtool
    - posix                  # [win]
    - {{p}}flex
    - {{p}}bison
    - {{n}}expat
  run:
    - {{n}}gcc-libs          # [win]
    - {{n}}expat

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles
    - conda inspect linkages -p $PREFIX udunits2  # [not win]
    - conda inspect objects -p $PREFIX udunits2  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: UCAR OSI approved
  license_file: COPYRIGHT
  summary: 'The UDUNITS package supports units of physical quantities.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - dkillick
    - mingwandroid
