travis:
  secure:
    BINSTAR_TOKEN: YU1pQvQDX3nVOQTruFFfqOZLtPM7l8zyMgnQl+yJMI1lqHUAsg348jYDwpyivuqx5/z0Dh53gcvsoK5lKJCZUSRNh6YOLknVMckY82m+hrSuG9xyU+Q0gBXtHEQEGqxouSdHITlPihCVnLexkk835PMdQ5vG1fwu7Zfdx+uUf6v8/bar9+E42WWAndNDghmezxApKxPDtKgSthPvPx4kyMmDwWnupdclZYEmt6LKTVFkJxD2v1gYa6yvABaoUCOUnscRg64aUFN/7wx3gbAdFGN01UuaMfNVUDF96W82Weu9Vwt2aRBk3f+ACVFvQ8peq74hQyx5IlL1SUdISlyO/b6ADiGsvY0TjRNiEJ05/bMS2j7FNE03P2dVbNZnMON4FzWdXgsxz4+wQ71wdEnglCGuTm47uaL9d8csatmDwg+BOUv+O96TGhqjiDnh4ErpXMQVjurtrydJBh7QNfiGkklBzz7z81z8hXulE64FKj9uc1OWh8W0oI/QLZZn0slVYCWZrMXzb89bNV//g4crgBtDzmu3TRK9EAiItE+FYYrIezm1CORHHNvfnur3/X8adXo5sPzFg1Tmi4stuGg/6U8aU1r3IbaqDsyu9jjHHt4vyl+mGU5o+FPS49oRXb48GeOtjA0Nxa2RmQgxmcdw6Yb5mMOYUd0REfbCb33QDwo=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
